name: Build Android APK
on: [push]

# Forza l'uso di Node 24 per evitare i warning di GitHub
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 24 # Usiamo l'ultima versione disponibile
          
      - name: Install Dependencies
        run: npm install
        
      - name: Add Android Platform
        run: npx cap add android
        
      - name: Copy Web Assets
        run: npx cap copy
        
      - name: Build Android Project
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: android/app/build/outputs/apk/debug/app-debug.apk
